apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: debug
  title: debug
  description: Template for debugging
  tags:
    - debug
spec:
  owner: Alef
  type: debug
  steps:
    - id: template
      name: Dotnet new webapi
      action: dotnet:new
      input:
        template: webapi
        args:
          - -n
          - MyWebApi

    - id: build
      name: Build app
      action: dotnet:build